### PR TITLE
fetch all repos from org

### PR DESCRIPTION
**Pull request by Arjun31415**

### CODE REVIEW

**Comment by Arjun31415** [comment]
Sample endpoint-
https://api.github.com/orgs/google/repos?per_page=100&page=4

**Comment by Arjun31415** [comment]
The Org avatar is being fetched multiple times. Can be fixed later

**Review by washbin — COMMENTED** [review]
Looks good to me

**Review by furtidev — APPROVED** [review]
Some changes need to be made, but it's fine for now. Good Work.

**Pull request merged**
